/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar_pktwisata_java;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Thailand extends javax.swing.JFrame {

    int Bint3, Bint4;
    String a, b, c;
    /**
     * Creates new form Singapore
     */
    public Thailand() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        PilPaket = new javax.swing.JComboBox<>();
        Tanggal = new javax.swing.JComboBox<>();
        Bulan = new javax.swing.JComboBox<>();
        Tahun = new javax.swing.JComboBox<>();
        DgnPesawat = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jumlah = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Pemesanan = new javax.swing.JTextArea();
        Keluar = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Cek = new javax.swing.JButton();
        Nama = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        NoKTP = new javax.swing.JTextField();
        NoHP = new javax.swing.JTextField();
        Hargatotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Pesan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("panTOURah");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 270, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar_pktwisata_java/p-white.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar_pktwisata_java/p-white.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar_pktwisata_java/thai1.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 109));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Pilih Paket");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel5.setText("Bintang ( Hotel )");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));

        jRadioButton1.setText("Bintang 3");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 24, -1, -1));

        jRadioButton2.setText("Bintang 4");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 50, -1, -1));

        jLabel6.setText("Tanggal Pergi");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        PilPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Paket", "Paket 1", "Paket 2", "Paket 3" }));
        PilPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilPaketActionPerformed(evt);
            }
        });
        jPanel2.add(PilPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 246, 22));

        Tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        Tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalActionPerformed(evt);
            }
        });
        jPanel2.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        Bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember", " " }));
        Bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanActionPerformed(evt);
            }
        });
        jPanel2.add(Bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        Tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        Tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunActionPerformed(evt);
            }
        });
        jPanel2.add(Tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        DgnPesawat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DgnPesawat.setText("Dengan Pesawat (PP)");
        DgnPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DgnPesawatActionPerformed(evt);
            }
        });
        jPanel2.add(DgnPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel7.setText("Harga");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, -1, -1));

        Harga.setText(" ");
        jPanel2.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 139, 204, -1));

        jLabel8.setText("Jumlah");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        Jumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahActionPerformed(evt);
            }
        });
        jPanel2.add(Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 277, 360, 170));

        jLabel9.setText("Nama Lengkap");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jLabel11.setText("No KTP");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel12.setText("No HP");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        jLabel14.setText("Harga Total");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        Pemesanan.setColumns(20);
        Pemesanan.setRows(5);
        getContentPane().add(Pemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 390, 211));

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, -1));

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, -1, -1));

        Cek.setText("Cek");
        Cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekActionPerformed(evt);
            }
        });
        getContentPane().add(Cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, -1, -1));

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 210, -1));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 210, -1));

        NoKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoKTPActionPerformed(evt);
            }
        });
        getContentPane().add(NoKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 210, 25));

        NoHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoHPActionPerformed(evt);
            }
        });
        getContentPane().add(NoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 210, -1));

        Hargatotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargatotalActionPerformed(evt);
            }
        });
        getContentPane().add(Hargatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 210, -1));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(972, 271, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar_pktwisata_java/thai3.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar_pktwisata_java/thai2.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Paket 1 ( 5 Days Tour)");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel20.setText("Paket 2 ( 7 Days Tour)");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        jLabel21.setText("Paket 3 ( 9 Days Tour)");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("Jelajahi Phang Nga Bay di Phuket dan keindahan pulau PhiPhi");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setText("Jelajahi Bangkok, Kanchanaburi, Ayutthaya, dan Patthaya");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("Jelajahi Bangkok, Patthaya, Phuket, Krabi, dan keindahan pulau PhiPhi");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("*Harga Sudah Termasuk Pajak");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 135, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 360, -1));

        Pesan.setText("Pesan");
        Pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesanActionPerformed(evt);
            }
        });
        getContentPane().add(Pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected())
        {
            Harga.setText(Bint4+"");
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed
//if(jCombobox2.getSelectedItem("Pilih Paket"))
    private void PilPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilPaketActionPerformed
        // TODO add your handling code here:
        switch(PilPaket.getSelectedIndex())
        {
            case 0 :
                Harga.setText("");
                break;
            case 1 :
                Bint3 = 4300000;
                Bint4 = 5880000;
                break;
            case 2 :
                Bint3 = 6440000;
                Bint4 = 8750000;
                break;
            case 3 :
                Bint3 = 8930000;
                Bint4 = 11400000;
                break;
        }
    }//GEN-LAST:event_PilPaketActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
           Harga.setText(Bint3+""); 
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void TanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalActionPerformed
        // TODO add your handling code here:
        
        if(Tanggal.getSelectedItem().equals("Belum Diisi"))
        {
            a= "Belum Diisi";
        }
        else if (Tanggal.getSelectedItem().equals("1"))
        {
            a= "1";
        }
        else if (Tanggal.getSelectedItem().equals("2"))
        {
            a= "2";
        }
        else if (Tanggal.getSelectedItem().equals("3"))
        {
            a= "3";
        }
        else if (Tanggal.getSelectedItem().equals("4"))
        {
            a= "4";
        }
        else if (Tanggal.getSelectedItem().equals("5"))
        {
            a= "5";
        }
        else if (Tanggal.getSelectedItem().equals("6"))
        {
            a= "6";
        }
        else if (Tanggal.getSelectedItem().equals("7"))
        {
            a= "7";
        }
        else if (Tanggal.getSelectedItem().equals("8"))
        {
            a= "8";
        }
        else if (Tanggal.getSelectedItem().equals("9"))
        {
            a= "9";
        }
        else if (Tanggal.getSelectedItem().equals("10"))
        {
            a= "10";
        }
        else if (Tanggal.getSelectedItem().equals("11"))
        {
            a= "11";
        }
        else if (Tanggal.getSelectedItem().equals("12"))
        {
            a= "12";
        }
        else if (Tanggal.getSelectedItem().equals("13"))
        {
            a= "13";
        }
        else if (Tanggal.getSelectedItem().equals("14"))
        {
            a= "14";
        }else if (Tanggal.getSelectedItem().equals("15"))
        {
            a= "15";
        }else if (Tanggal.getSelectedItem().equals("16"))
        {
            a= "16";
        }else if (Tanggal.getSelectedItem().equals("17"))
        {
            a= "17";
        }else if (Tanggal.getSelectedItem().equals("18"))
        {
            a= "18";
        }else if (Tanggal.getSelectedItem().equals("19"))
        {
            a= "19";
        }else if (Tanggal.getSelectedItem().equals("20"))
        {
            a= "20";
        }else if (Tanggal.getSelectedItem().equals("21"))
        {
            a= "21";
        }else if (Tanggal.getSelectedItem().equals("22"))
        {
            a= "22";
        }else if (Tanggal.getSelectedItem().equals("23"))
        {
            a= "23";
        }else if (Tanggal.getSelectedItem().equals("24"))
        {
            a= "24";
        }else if (Tanggal.getSelectedItem().equals("25"))
        {
            a= "25";
        }else if (Tanggal.getSelectedItem().equals("26"))
        {
            a= "26";
        }else if (Tanggal.getSelectedItem().equals("27"))
        {
            a= "27";
        }else if (Tanggal.getSelectedItem().equals("28"))
        {
            a= "28";
        }else if (Tanggal.getSelectedItem().equals("29"))
        {
            a= "29";
        }else if (Tanggal.getSelectedItem().equals("30"))
        {
            a= "30";
        }else if (Tanggal.getSelectedItem().equals("31"))
        {
            a= "31";
        }
    }//GEN-LAST:event_TanggalActionPerformed

    private void DgnPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DgnPesawatActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            Harga.setText(Bint3+4200000+"");
        }
        else if(jRadioButton2.isSelected())
        {
            Harga.setText(Bint4+7200000+"");
        }
    }//GEN-LAST:event_DgnPesawatActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void NoKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoKTPActionPerformed

    private void NoHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoHPActionPerformed

    private void HargatotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargatotalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_HargatotalActionPerformed

    private void CekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekActionPerformed
        // TODO add your handling code here:
        Pemesanan.setText("Nama Lengkap : " + Nama.getText()
        + "\n" + "Email : " +                 Email.getText()
        + "\n" + "No KTP : " +                NoKTP.getText()
        + "\n" + "No HP : "  +                NoHP.getText()
        + "\n" + "Harga Total Pemesanan : Rp " + Hargatotal.getText()
        + "\n" + "Tanggal Pergi : "+ a + " " + b + " " + c + " "
        );
        
    }//GEN-LAST:event_CekActionPerformed

    private void JumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(Harga.getText());
        switch(Jumlah.getSelectedIndex())
        {
            case 0 :
            Hargatotal.setText("");
            break;
            case 1 :
            Hargatotal.setText(x * 1 + "");
            break;
            case 2 : 
            Hargatotal.setText(x * 2 + "");
            break;
            case 3 : 
            Hargatotal.setText(x * 3 + "");
            break;
            case 4 : 
            Hargatotal.setText(x * 4 + "");
            break;
            case 5 : 
            Hargatotal.setText(x * 5 + "");
            break;
            case 6 : 
            Hargatotal.setText(x * 6 + "");
            break;
            case 7 : 
            Hargatotal.setText(x * 7 + "");
            break;
            case 8 : 
            Hargatotal.setText(x * 8 + "");
            break;
            case 9 : 
            Hargatotal.setText(x * 9 + "");
            break;
            case 10 : 
            Hargatotal.setText(x * 10 + "");
            break;
        }
    }//GEN-LAST:event_JumlahActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(this,
        "Apa kamu yakin ingin keluar?",
        "Keluar Dari Program", JOptionPane.YES_NO_CANCEL_OPTION);
        if (pilihan == JOptionPane.YES_OPTION) System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        // TODO add your handling code here:
        new PilihDestinasi2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Thailand reset = new Thailand();
        reset.setVisible(false);
        reset.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ResetActionPerformed

    private void BulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanActionPerformed
        // TODO add your handling code here:
        if(Bulan.getSelectedItem().equals("Bulan"))
        {
            b="Bulan";
        }
        else if (Bulan.getSelectedItem().equals("Januari"))
        {
            b = "Januari";
        }
        else if (Bulan.getSelectedItem().equals("Februari"))
        {
            b = "Februari";
        }
        else if (Bulan.getSelectedItem().equals("Maret"))
        {
            b = "Maret";
        }
        else if (Bulan.getSelectedItem().equals("April"))
        {
            b = "April";
        }
        else if (Bulan.getSelectedItem().equals("Mei"))
        {
            b = "Mei";
        }
        else if (Bulan.getSelectedItem().equals("Juni"))
        {
            b = "Juni";
        }
        else if (Bulan.getSelectedItem().equals("Juli"))
        {
            b = "Juli";
        }
        else if (Bulan.getSelectedItem().equals("Agustus"))
        {
            b = "Agustus";
        }
        else if (Bulan.getSelectedItem().equals("September"))
        {
            b = "September";
        }
        else if (Bulan.getSelectedItem().equals("Oktober"))
        {
            b = "Oktober";
        }
        else if (Bulan.getSelectedItem().equals("November"))
        {
            b = "November";
        }
        else if (Bulan.getSelectedItem().equals("Desember"))
        {
            b = "Desember";
        }
    }//GEN-LAST:event_BulanActionPerformed

    private void TahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunActionPerformed
        // TODO add your handling code here:
        if (Tahun.getSelectedItem().equals("Tahun"))
        {
            c = "Tahun";
        }
        else if (Tahun.getSelectedItem().equals("2020"))
        {
            c = "2020";
        }
        else if (Tahun.getSelectedItem().equals("2021"))
        {
            c = "2021";
        }
        else if (Tahun.getSelectedItem().equals("2022"))
        {
            c = "2022";
        }
        else if (Tahun.getSelectedItem().equals("2023"))
        {
            c = "2023";
        }
        else if (Tahun.getSelectedItem().equals("2024"))
        {
            c = "2024";
        }
        else if (Tahun.getSelectedItem().equals("2025"))
        {
            c = "2025";
        }
        else if (Tahun.getSelectedItem().equals("2026"))
        {
            c = "2026";
        }
        else if (Tahun.getSelectedItem().equals("2027"))
        {
            c = "2027";
        }
        else if (Tahun.getSelectedItem().equals("2028"))
        {
            c = "2028";
        }
        else if (Tahun.getSelectedItem().equals("2029"))
        {
            c = "2029";
        }
        else if (Tahun.getSelectedItem().equals("2030"))
        {
            c = "2030";
        }
    }//GEN-LAST:event_TahunActionPerformed

    private void PesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesanActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(Cek, "Transaksi Anda Berhasil \n"
                + "Silahkan Cek Email anda untuk Pembayaran secara Detail");
    }//GEN-LAST:event_PesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thailand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thailand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thailand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thailand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thailand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bulan;
    private javax.swing.JButton Cek;
    private javax.swing.JCheckBox DgnPesawat;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Hargatotal;
    private javax.swing.JComboBox<String> Jumlah;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Kembali;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField NoHP;
    private javax.swing.JTextField NoKTP;
    private javax.swing.JTextArea Pemesanan;
    private javax.swing.JButton Pesan;
    private javax.swing.JComboBox<String> PilPaket;
    private javax.swing.JButton Reset;
    private javax.swing.JComboBox<String> Tahun;
    private javax.swing.JComboBox<String> Tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
